### ISSUE TITLE
Similar Project

### ISSUE THREAD

**Issue by capstonednc** [DevangPatel18/Map-Quiz#22]
This is amazing! I'm learning React and am building a similar project! How your project is organized is very clean and uncluttered. I'd love some feedback on my project if you can offer it. 

https://github.com/capstonednc/geography-app

**Comment by DevangPatel18** [comment]
Thanks! I'm curious how you found it though?

I looked at your website and it seems like it's off to a good start, though there's a few errors I ran into.

- Some of the country links lead to an error (Cannot read property 'government' of undefined).
- Trying to start a new game after completing a "Questions" quiz shows a "Game Over" prompt instead of starting a new quiz. Also, clicking an answer for the newly generated question leads to an error (TypeError: q.filter is not a function)

Noticed the following problems for the country specific pages.
- The star for marking a country as a favorite leads to a blank page.
- Having the favorite star occupy more than half of the horizontal space seems like a waste. You could put more interesting info like the country itself on the map, breakdown of the demographic, gdp, founding date, etc.
- The nested structure of all the information could be improved using tables and charts.
- There's console messages firing every few seconds or so
